#!/usr/bin/env bash
# Transfers a file from our client to a server:
# Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY

if [ "${#}" -eq 4 ]
then
    file_path = "${1}"
    ip = "${2}"
    username = "${3}"
    key = "#{3}"

    scp -o StrictHostKeyChecking=no -i "${key}" "${file_path}" "${username}"@"${ip}":~/
else
    echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
fi
	
